import { ServerIcon } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * Distribution logos are static files generated by scripts/assets.ts, keyed by
 * the slug of the system name. Specific names come before the generic "linux",
 * which several of their strings contain.
 */
const MATCHES: [string[], string][] = [
  [["debian"], "debian"],
  [["ubuntu"], "ubuntu"],
  [["alpine"], "alpinelinux"],
  [["centos"], "centos"],
  [["rocky"], "rockylinux"],
  [["alma"], "almalinux"],
  [["fedora"], "fedora"],
  [["arch"], "archlinux"],
  [["opensuse"], "opensuse"],
  [["suse", "sles"], "suse"],
  [["red hat", "redhat", "rhel"], "redhat"],
  [["freebsd"], "freebsd"],
  [["openbsd"], "openbsd"],
  [["netbsd"], "netbsd"],
  [["gentoo"], "gentoo"],
  [["proxmox"], "proxmox"],
  [["mint"], "linuxmint"],
  [["nixos"], "nixos"],
  [["raspbian", "raspberry"], "raspberrypi"],
  [["kali"], "kalilinux"],
  [["linux"], "linux"],
];

/** One icon per distribution, in its brand colour. Unknown systems get a
 *  neutral server glyph rather than a wrong logo. */
export function OsIcon({ os, className }: { os: string; className?: string }) {
  const lower = os.toLowerCase();
  const slug = MATCHES.find(([keys]) => keys.some((k) => lower.includes(k)))?.[1];
  if (!slug) {
    return (
      <ServerIcon
        className={cn("size-4 text-muted-foreground", className)}
        aria-label={os || "未知系统"}
      />
    );
  }
  return (
    <img
      src={`/os/${slug}.svg`}
      alt={os || slug}
      title={os || slug}
      width={16}
      height={16}
      loading="lazy"
      className={cn("size-3.5 sm:size-4", className)}
    />
  );
}
